import { clsx, type ClassValue } from 'clsx';
import { twMerge } from 'tailwind-merge';

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

/**
 * Decodes a barcode string that may have been generated by a physical laser scanner (douchette)
 * configured in keyboard emulation (e.g., QWERTY but typed on a French AZERTY layout system).
 * 
 * Supports standard formats: EAN-13, EAN-8, UPC, Code 128, etc.
 * Normalizes text, cleans control characters, differences between layouts,
 * and maintains only digits as requested ("Le champ doit afficher uniquement les chiffres").
 */
export function decodeAzertyBarcode(str: string): string {
  if (!str) return '';

  // 1. Log the RAW value received from the scanner
  console.log(`[SCANNER RAW VALUE] Valeur brute reçue: "${str}"`);

  // 2. Log ASCII codes of each character to assist debugging
  const asciiLogs = Array.from(str)
    .map(c => `"${c}" (ASCII: ${c.charCodeAt(0)})`)
    .join(', ');
  console.log(`[SCANNER ASCII CODES] ${asciiLogs}`);

  // Normalization to NFC (Normalization Form Canonical Composition) and cleaning UTF-8 / carriage controls
  let cleanStr = str.normalize('NFC');
  
  // Character mapping for QWERTY to AZERTY emulation
  // Top row translation for French/Belgian keyboard layouts
  const azertyToQwertyMap: Record<string, string> = {
    // Standard French AZERTY numbers row (unshifted keys)
    '&': '1',
    'é': '2',
    '"': '3',
    '\'': '4',
    '(': '5',
    '-': '6',
    '§': '6', // Belgian AZERTY 6
    'è': '7',
    '_': '8',
    '!': '8', // Belgian AZERTY 8
    'ç': '9',
    'à': '0',
    '°': '0', // Shift-0 / Belgian 0 helper
    ')': '0',
    
    // Shift row variants if caps-lock or alternate emulation triggers
    'Q': 'A', 'W': 'Z', 'A': 'Q', 'Z': 'W', 'M': ',',
    'q': 'a', 'w': 'z', 'a': 'q', 'z': 'w', 'm': ',',
  };

  let decodedBuilder = '';
  for (let i = 0; i < cleanStr.length; i++) {
    const char = cleanStr[i];
    
    // Skip carriage returns, line breaks, null/control characters or spaces
    if (char === ' ' || char === '\xa0' || char === '\r' || char === '\n' || char === '\t' || char.charCodeAt(0) < 32 || char.charCodeAt(0) === 127) {
      continue;
    }

    if (azertyToQwertyMap[char] !== undefined) {
      decodedBuilder += azertyToQwertyMap[char];
    } else {
      decodedBuilder += char;
    }
  }

  // Adhere to: "Le champ doit afficher uniquement les chiffres du code-barres scanné."
  // Strip all non-digit characters in the final output
  const finalDigits = decodedBuilder.replace(/[^0-9]/g, '');

  // Detect and log the barcode type (EAN-13, EAN-8, UPC, Code 128, etc.)
  let detectedType = 'Code 128 / Personnalisé';
  if (/^[0-9]{13}$/.test(finalDigits)) {
    detectedType = 'EAN-13 (Standard International)';
  } else if (/^[0-9]{8}$/.test(finalDigits)) {
    detectedType = 'EAN-8 (Standard Compact)';
  } else if (/^[0-9]{12}$/.test(finalDigits)) {
    detectedType = 'UPC-A (Standard USA)';
  } else if (finalDigits.length === 11 || finalDigits.length === 12) {
    detectedType = 'UPC / UPC-E';
  } else if (/^[0-9]+$/.test(finalDigits)) {
    detectedType = `Code 128 (Numérique, longueur ${finalDigits.length})`;
  } else if (finalDigits.length === 0) {
    detectedType = 'Aucune figure valide détectée';
  }

  console.log(`[SCANNER DECODED SUMMARY] Type de code-barres détecté: ${detectedType}`);
  console.log(`[SCANNER DECODED RESULT] Chiffres décodés purs: "${finalDigits}"`);

  return finalDigits;
}

