import { clsx, type ClassValue } from 'clsx';
import { twMerge } from 'tailwind-merge';

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

/**
 * Decodes a barcode string that may have been generated by a physical laser scanner (douchette)
 * configured in QWERTY but typed on a French AZERTY layout system.
 * It also strips spaces, which are commonly sent by scanner keyboard emulations.
 */
export function decodeAzertyBarcode(str: string): string {
  if (!str) return '';
  
  const map: Record<string, string> = {
    '&': '1',
    'é': '2',
    '"': '3',
    '\'': '4',
    '(': '5',
    '-': '6',
    '§': '6', // Belgian AZERTY key for 6
    'è': '7',
    '_': '8',
    '!': '8', // Belgian AZERTY key for 8
    'ç': '9',
    'à': '0',
    '°': '0', // Shift-0 helper
  };
  
  let decoded = '';
  for (let i = 0; i < str.length; i++) {
    const char = str[i];
    if (map[char] !== undefined) {
      decoded += map[char];
    } else if (/[0-9]/.test(char)) {
      decoded += char;
    } else if (char === ' ' || char === '\xa0' || char === '\r' || char === '\n') {
      // Ignore whitespaces or carriage returns sent by the scanner
      continue;
    } else {
      decoded += char;
    }
  }
  return decoded;
}

